name: 'Publish Storybook to Chromatic'

on:
  push:

jobs:
  publish-storybook-to-chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: 'yarn'
      - run: yarn
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          exitZeroOnChanges: true
          onlyChanged: true
        env:
          STORYBOOK_API_BASE_URL: ${{ vars.STORYBOOK_API_BASE_URL }}
